#! /usr/bin/env python
#This script will pull the final atom positions out of a cp2k output file which has '-pos-#.xyz' format
import readline
import subprocess

#get positions file name and system name
fN = subprocess.Popen(r'ls *pos*', stdout=subprocess.PIPE, shell=True)
fileName = str(fN.communicate()[0]).rstrip("\n")
#create the string of the output file's name:
outputName = 'finalPositions' + fileName.rsplit('-',2)[0] + '.xyz'
#open the file and read the number of atoms from the first line, storing the number as an int
positionFile = open(fileName,'r')
atomsNumber = int(positionFile.readline())
positionFile.close()
#to create a proper xyz file, the total number of lines we need is the number of atoms plus two additional lines, one containing the number of atoms, and the other being the comment line. We already have the number of atoms from above. Therefore, we need to get the comment line and the atom positions from the final iteration, which are the last 1 + atomsNumber lines of the file.
#read in all lines
positionFile2 = open(fileName,"r")
lines = positionFile2.readlines()
positionFile2.close()
#determine total number of lines
numOfLines = len(lines)
#what line is the first one that we actually want? Python indexes from 0, so we need:
firstLine = numOfLines - atomsNumber - 2
#because numOfLines will have the integer number of lines.
#open the file for the final positions:
finalPositions = open(outputName,'a')
#now the loop
for j, line in enumerate(lines):
    if j >= firstLine:
        finalPositions.write(line)
finalPositions.close()
